apps/login_reg/urls.py
from django.conf.urls import url,include
import views

urlpatterns = [ 
    url(r'^$', views.index, name='signup'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$',views.registration, name='register'),
    url(r'^logout$', views.logout, name='logout' ),
    url(r'^success$', views.success, name='success' ),
]

d_appointments/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('apps.login_reg.urls', namespace='home')),
    url(r'^appointments/', include('apps.main_app.urls', namespace='dashboard')),
    
]

apps/login_reg/models.py
from __future__ import unicode_literals
from django.db import models
import re  # import python regex module
import bcrypt


EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
DATE_REGEX = re.compile(r'^[0-9]{2}\/[0-9]{2}\/[0-9]{4}$')
class UserManager(models.Manager):
    
        def registration(self, data):
            errors = []
            
            if len(data['first_name']) < 2:
                errors.append("first name is empty or needs more 2 chars")
            if len(data['last_name']) < 2:
                errors.append("last name is empty  or needs more 2 chars")
            if len(data['email']) < 1:
                errors.append(" email is empty")
            if not EMAIL_REGEX.match(data['email']):
                errors.append(" email is not valid")    
            if not DATE_REGEX.match(data['date_hired']):
                errors.append(" date is not valid")                    
            if len(data['password']) < 8:
                errors.append("password is empty  or needs more 8 chars")                 
            if len(data['confirm_ps']) < 8:
                errors.append("confirm password is empty  or needs more 8 chars")
                
            if data['confirm_ps'] != data['password'] :
                errors.append("password and confirm password are not equal")
            if len(errors) == 0:
                user = self.filter(email=data['email'])            
                if user :
                    errors.append("user alraedy exist")
                    
            msgRsp = {}
            
            if len(errors) > 0:
                msgRsp['status'] = False
                msgRsp['errors'] = errors
            else :
                hashed_password = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
                user = self.create(first_name=data['first_name'],
                            last_name=data['last_name'],
                            email=data['email'],
                            password=hashed_password)
                msgRsp['status'] = True
                msgRsp['user'] = user
                
            return msgRsp    
            
        def login(self, data):
            
            msgRsp = {}            
            errors = []
            
            if len(data['email']) < 1:
                errors.append(" email is empty")
            if not EMAIL_REGEX.match(data['email']):
                errors.append(" email is not valid")
            if len(data['password']) < 8:
                errors.append("password is empty  or needs more 8 chars") 
                
            if len(errors) == 0:
                user = self.filter(email=data['email'])            
                if user :
                    if bcrypt.checkpw(data['password'].encode(), user[0].password.encode()):
                        msgRsp['status'] = True
                        msgRsp['user'] = user[0]
                    else :
                        errors.append("Invalid password try again")
                        msgRsp['status'] = False
                        msgRsp['errors'] = errors
                else :  
                    errors.append("Invalid user try again")
                    msgRsp['status'] = False
                    msgRsp['errors'] = errors
            else :
                msgRsp['status'] = False
                msgRsp['errors'] = errors
            return msgRsp

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=34)
    last_name = models.CharField(max_length=34)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=256)
    created_at =  models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/login_reg/views.py
from django.shortcuts import render, redirect,HttpResponse
from models import User

from django.contrib import messages
# Create your views here.
def index(request):
    return render(request, 'login_reg/index.html')

def registration(request):
    if request.method == "POST":
        model_rsp = User.objects.registration(request.POST)  
        if  model_rsp['status']:
            request.session['user_id'] = model_rsp['user'].id
            request.session['user'] = model_rsp['user'].first_name            
            return redirect('home:success')
        else:
            for error in model_rsp['errors']:
                messages.error(request, error)
    return redirect('home:signup')
                
def login(request):

    if request.method == 'POST': 
        model_rsp = User.objects.login(request.POST)
        if  model_rsp['status']:
            request.session['user_id'] = model_rsp['user'].id
            request.session['user'] = model_rsp['user'].first_name            
            return redirect('home:success')
        else:
            for error in model_rsp['errors']:
                messages.error(request, error)
    return redirect('home:signup')
    
def logout(request):

    if request.method == "POST":
        if 'user_id' in request.session:
           request.session.pop('user_id')
           request.session.pop('user')
    request.session['user_status'] = 'logged out'   
    return redirect("home:signup" )
    
def success(request):
    if 'user_id' in request.session: 
        request.session['user_status']  = 'logged in'  
        return redirect('dashboard:home')
    else :
        return redirect('home' )

apps/login_reg/templates/login_reg/index.html
<!DOCTYPE hmtl>
<html>
    <head>
        <meta charset="utf8" />
        <meta name="descripition" content="Learning about Django"/>
        <title>Courses</title>
        
        {% load static %}
        <link rel="stylesheet" href={% static "first_app/css/index.css"  %}></link>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script type="text/javascript" src={% static "first_app/js/index.js"  %}></script> 
        <style>
            label {
                   vertical-align:top;
                   display:inline-block;
                   width:130px;
                   text-align:right;
            }
            form input {                
                margin-bottom:10px;
                margin-left:5px;
            }
            form input[type=submit] {
                margin-left:230px;
                width:80px;
                color:white;
                background-color:blue;
            }            
        </style>
       
    </head>
    <body>
        <div id="container"> 
            <form  action="{% url 'home:register' %}"  method="post">
                {% csrf_token %}
                <h4>Registration</h4>
                  {% for message in messages %}
                    <p>{{ message }}</p>
                  {% endfor %}
                <label>First Name:</label><input type="text" name="first_name"/><br>
                <label>Last Name:</label><input type="text" name="last_name"/><br>
                <label>Email:</label><input type="email" name="email"/><br>
                <label>Password:</label><input type="password" name="password"/><br>
                <label>Confirm Password:</label><input type="password" name="confirm_ps"/><br>
                <label>Date Hired:</label><input type="text" name="date_hired" placeHolder="MM/DD/YYYY"/><br>
                
                <input type="submit" name="resgiter" value="Resgiter"/><br>                
            </form> 

            <form  action="{% url 'home:login' %}"  method="post">
                {% csrf_token %}
                <h3>Login</h3>
                <label>Email:</label><input type="email" name="email"/><br>
                <label>Password:</label><input type="password" name="password"/><br>                
                <input type="submit" name="login" value="Login"/><br>                
            </form>        
                                
                              
        </div>
    </body>
</html>

apps/login_reg/templates/login_reg/success.html
<!DOCTYPE hmtl>
<html>
    <head>
        <meta charset="utf8" />
        <meta name="descripition" content="Learning about Django"/>
        <title>Courses</title>
        
        {% load static %}
        <link rel="stylesheet" href={% static "first_app/css/index.css"  %}></link>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script type="text/javascript" src={% static "first_app/js/index.js"  %}></script> 
        <style>
            p{
                color:green;
             }
             table, th, td {
                border: 1px solid black;
                padding: 15px;
            }
        </style>
       
    </head>
    <body>
        <div id="container"> 
            <h2>Sucess! Welcome, {{first_name}}!</h2>
            <p><small>Succesfully {{status}}</small></p>
            
            <form  action="{% url 'courses:create_user' %}"  method="post">
                {% csrf_token %} 
                <select name="user_id">
                    {% for user in users %} 
                    <option value='{{user.id}}'>{{user.first_name}}_{{user.last_name}}</option>'
                    {% endfor %}
                </select>
                 <select name="course_id">
                    {% for course in courses %} 
                    <option value='{{course.id}}'>{{course.course_name}}</option>
                    {% endfor %}
                </select>
                  
                <input type="submit" value="Add User To Course"/>              
            </form>
            
            <div id="courses_user_distro">
                <table>
                    <th>Course</th>
                    <th>Title</th>
                    <th>Numbero of Users</th>
                    {% for course in courses %}
                        <tr>
                            <td>{{course.id}}</td> 
                            <td>{{course.course_name}}</td>  
                            <td>{{course.users.count}}</td>                             
                        </tr>
                    {% endfor %}
                </table>
                                  
            </div> 
            <br>
            <form  action="/logout"  method="post">
                {% csrf_token %}               
                <input type="submit" value="logout"/>              
            </form>
                                  
        </div>
    </body>
</html>