apps/login_reg/urls.py
from django.conf.urls import url,include
import views

urlpatterns = [ 
    url(r'^$', views.index, name='signup'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$',views.registration, name='register'),
    url(r'^logout$', views.logout, name='logout' ),
    url(r'^success$', views.success, name='success' ),
]

apps/main_app/urls.py
from django.conf.urls import url
import views

urlpatterns = [ 
    url(r'^$', views.index, name='home'),
    url(r'^create$', views.add, name='create'),
    url(r'^(?P<task_id>\d+)/show$', views.showUpdate, name='show_update'),
    url(r'^(?P<task_id>\d+)/udpate$', views.update, name='update'),
    url(r'^(?P<task_id>\d+)$', views.showDelete, name='show_delete'),
    url(r'^(?P<task_id>\d+)/delete$', views.delete, name='delete')
   
    
]

d_appointments/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('apps.login_reg.urls', namespace='home')),
    url(r'^appointments/', include('apps.main_app.urls', namespace='dashboard')),
    
]

apps/main_app/models.py
from __future__ import unicode_literals

from django.db import models
from ..login_reg.models import User
from datetime import datetime
import re  # import python regex module
# Create your models here. 

DATE_REGEX = re.compile(r'^[0-9]{2}\/[0-9]{2}\/[0-9]{4}$')
TIME_REGEX = re.compile(r'^[0-9]{2}:[0-9]{2}$')
   
   
class AppointmentManager(models.Manager):
       
    def validateTaskData(self, data):
        print "doing vlaidation"
        errors = []

        if len(data['task']) < 1:
            errors.append("Task info is empty")
        if len(data['status']) < 1:
            errors.append("Missing status")
        if len(data['date']) < 1:
            errors.append(" date is empty")               
        if not DATE_REGEX.match(data['date']):
            errors.append("date is not valid")                    
        if len(data['time']) < 1:
            errors.append("time is empty")                 
        if not TIME_REGEX.match(data['time']):
            errors.append("time is not valid") 
            
        if len(errors) == 0:    
            strdatetime =  data['date'] + " " + data['time']
            datetime_object = datetime.strptime(strdatetime, '%m/%d/%Y %H:%M')

            if datetime_object < datetime.now():
                errors.append("date and time is not of the current of future date")
            
        if len(errors):
            return {'status':True, 'errors':errors}
        else:
            return {'status':False, 'datetime':datetime_object}   
            
    def getCurrentTasks(self, user_id):
        today = datetime.now()
        tasks =  self.filter(user__id=user_id, 
        taskdatetime__year=today.year,
        taskdatetime__month=today.month, 
        taskdatetime__day=today.day).order_by('taskdatetime')
        return tasks
       
    def getFutureTasks(self, user_id):       
        today = datetime.now()
        print today
        tasks =  self.exclude(taskdatetime__date__lte=today.date(),                            
                            ).filter(user__id=user_id,).order_by('taskdatetime')
        return tasks
        
    def getTask(self, task_id):             
        usrtask = self.get(id=task_id)
        return usrtask
        
    def deleteTask(self, task_id):
        rsp = {}
        rsp['status'] = False
        try :    
            usrtask = self.get(id=task_id)
            usrtask.delete()
        except DoesNotExist:
            rsp['status'] = True
            rsp['errors'] = ["Appointment matching query does not exist"]
        return rsp 
        
        
        
    def addTask(self,user_id, postData):
    
        rsp = self.validateTaskData(postData)
        print "done with validation"
        print rsp
        if rsp['status'] : # if validation errors
            return rsp
        else :
            try  :
                req_datetime = rsp['datetime'] 
                user = User.objects.get(id=user_id)                
                task = self.create(task=postData['task'], user=user, taskdatetime=req_datetime,  status=postData['status'])
                print task
            except:
                rsp['status'] = True
                rsp['errors'] = ["Duplicate error."]
            return rsp

    def updateTask(self,user_id, task_id, postData):
    
        rsp = self.validateTaskData(postData)
        if rsp['status'] : # if validation errors
            return rsp
        else :
            req_datetime = rsp['datetime'] 
            user = User.objects.get(id=user_id) 
            try :            
                usrtask = self.get(id=task_id)
                usrtask.task=postData['task']
                usrtask.user=user 
                usrtask.taskdatetime=req_datetime
                usrtask.status=postData['status'] 
                usrtask.save()
            except :
                rsp['status'] = True
                rsp['errors'] = ["Either the entry or blog doesn't exist or Duplicate error."]
            return rsp        
    
                
class Appointment(models.Model):
    
    task=models.CharField(max_length=3000)  
    user=models.ForeignKey(User, related_name='task_added_by')
    taskdatetime=models.DateTimeField(auto_now=False, auto_now_add=False)
    status=models.CharField(max_length=30) 
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)    
    objects=AppointmentManager()
    
    class Meta:
        unique_together = (("user", "taskdatetime"),)
    

apps/main_app/views.py
from django.shortcuts import render ,redirect
from models import Appointment
from django.contrib import messages
from datetime import datetime

# Create your views here.
def index(request):
    
    try:
        context = {
                'first_name': request.session['user'],
                'login_id': request.session['user_id'],
                'status': request.session['user_status'], 
                'task_date':datetime.now(),
                'current_appointments': Appointment.objects.getCurrentTasks(request.session['user_id']),
                'other_appointments':Appointment.objects.getFutureTasks(request.session['user_id'])                
            }        
        
        return render( request, 'main_app/index.html', context)
    except KeyError:
            return redirect('home:signup')         



def add(request):
    
    if request.method == 'POST':
        try:
            context = {
                    'first_name': request.session['user'],
                    'status': request.session['user_status'],                             
                }
                
            print context
            rsp = Appointment.objects.addTask(request.session['user_id'], request.POST)  
            print rsp            
            if rsp['status'] :            
                for error in rsp['errors']:
                    messages.error(request, error)
            return redirect('dashboard:home')
        except KeyError:
                return redirect('home:signup')
                
def showUpdate(request, task_id):
   
    try:
        context = {
                'first_name': request.session['user'],
                'status': request.session['user_status'], 
                'appointment':Appointment.objects.getTask(task_id)
            }        
        
        return render( request, 'main_app/update.html', context)
    except KeyError:
            return redirect('home:signup')

def showDelete(request, task_id):
   
    try:
        context = {
                'first_name': request.session['user'],
                'status': request.session['user_status'], 
                'appointment':Appointment.objects.getTask(task_id)
            }       
        
        return render( request, 'main_app/delete.html', context)
    except KeyError:
            return redirect('home:signup')

            
def update(request, task_id):   
   
   if request.method == 'POST':
        try:
            context = {
                    'first_name': request.session['user'],
                    'status': request.session['user_status'],                             
                }
                
            print context
            rsp = Appointment.objects.updateTask(request.session['user_id'], task_id, request.POST) 
            print rsp            
            if rsp['status'] :            
                for error in rsp['errors']:
                    messages.error(request, error)
                return redirect('dashboard:show_update',  task_id)
            else:
                return redirect('dashboard:home')
        except KeyError:
                return redirect('home:signup')
            
def delete(request, task_id):
    
    if request.method == 'POST':
        try:
            context = {
                    'first_name': request.session['user'],
                    'status': request.session['user_status'],                             
                }
            rsp = Appointment.objects.deleteTask(task_id)  
            print rsp
            if rsp['status'] :            
                for error in rsp['errors']:
                    messages.error(request, error)
                return redirect('dashboard:show_delete',  task_id)
            else:
                return redirect('dashboard:home')         
        except KeyError:
            return redirect('home:signup')

apps/main_app/templates/main_app/delete.html
<!DOCTYPE hmtl>
<html>
    <head>
        <meta charset="utf8" />
        <meta name="descripition" content="Learning about Django"/>
        <title>Courses</title>
        
        {% load static %}
        <link rel="stylesheet" href={% static "first_app/css/index.css"  %}></link>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script type="text/javascript" src={% static "first_app/js/index.js"  %}></script> 
        <style>
            label {
                   margin:20px;
                   margin-left:0px;
                   vertical-align:top;
            }
            form input {
                margin-left:40px;
                margin-bottom:10px;
            }
            form input[type=submit] {
                margin-left:400px;
                height:45px;
                width:80px;
                color:white;
                background-color:blue;
            }
            
            
            
        </style>
       
    </head>
    <body>
        <div id="container"> 
           <form  action="{% url 'dashboard:delete'  task_id=appointment.id %}"  method="post">
                {% csrf_token %}
                <h4>Add Appoint</h4>
                  {% for message in messages %}
                    <p>{{ message }}</p>
                  {% endfor %}
                <label>Date:</label><input type="text" name="date" placeHolder="MM/DD/YYYY"  value='{{appointment.taskdatetime|date:"m/d/Y"}}'/><br>
                <label>Time:</label><input type="text" name="time" placeHolder="HH:MM" value='{{appointment.taskdatetime|date:"H:i"}}'/><br>
                <label>Tasks:</label><input type="text" name="task" value='{{appointment.task}}'><br>
                <label>Status:</label>
                <select name="status" value='{{appointment.status}}'>
                  <option value="Pending">Pending</option>
                  <option value="Done">Done</option>                  
                </select><br>                 
                <input type="submit" name="add" value="Delete"/><br>                
            </form>         
            <a href="{% url 'dashboard:home' %}">Home</a>   |      <a href="{% url 'home:logout' %}">Logout</a>
                      
        </div>
    </body>
</html>

apps/main_app/templates/main_app/index.html
<!DOCTYPE hmtl>
<html>
    <head>
        <meta charset="utf8" />
        <meta name="descripition" content="Learning about Django"/>
        <title>Courses</title>
        
        {% load static %}
        <link rel="stylesheet" href={% static "first_app/css/index.css"  %}></link>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script type="text/javascript" src={% static "first_app/js/index.js"  %}></script> 
        <style>
            p{
                color:green;
             }
             table, th, td {
                border: 1px solid black;
                padding: 5px;
            }
        </style>
       
    </head>
    <body>
        <div id="container"> 
            <h2>Sucess! Welcome, {{first_name}}!</h2>
            <p><small>Succesfully {{status}}</small></p>
            
            <form  action="{% url 'home:logout' %}"  method="post">
                {% csrf_token %}               
                <input type="submit" value="logout"/>              
            </form>  
            
            <div id="my_appoitments">
                <p>Here are appintments for today,{{ task_date|date:"D d M Y" }} </p>
                
                <table>
                    <th>Task</th>
                    <th>Time</th>
                    <th>Status</th> 
                    <th>Action</th>                    
                    {% for appointment in current_appointments %}
                        <tr>
                            <td>{{appointment.task}}</td> 
                            <td>{{appointment.taskdatetime|date:"H:i"}}</td>  
                            <td>{{appointment.status}}</td> 
                            {% if appointment.status == "Pending" %} 
                                <td>
                                    <a href="{% url 'dashboard:show_update' task_id=appointment.id %}" >Edit</a>  
                                    <a href="{% url 'dashboard:show_delete' task_id=appointment.id %}">Delete</a>
                                </td>
                            
                                
                            {% endif %}                            
                        </tr>
                    {% endfor %}
                </table>                                  
            </div> 
            <br>
            <div id="other_appointments">
                <p>Your Other appointments</p>
                <table>
                    <th>Task</th>
                    <th>Date</th> 
                    <th>Time</th>                                                         
                    {% for appointment in other_appointments %}
                        <tr>
                            <td>{{appointment.task}}</td> 
                            <td>{{ appointment.taskdatetime|date:"D d M Y" }}</td> 
                            <td>{{appointment.taskdatetime|date:"H:i"}}</td>  
                                                                               
                        </tr>
                    {% endfor %}
                </table>                                  
            </div>  

            <form  action="{% url 'dashboard:create' %}"  method="post">
                {% csrf_token %}
                <h4>Add Appointment</h4>
                  {% for message in messages %}
                    <p>{{ message }}</p>
                  {% endfor %}
                <label>Date:</label><input type="text" name="date" placeHolder="MM/DD/YYYY"/><br>
                <label>Time:</label><input type="text" name="time" placeHolder="HH:MM"/><br>
                <label>Tasks:</label><input type="text" name="task"/><br>
                <input type="hidden" name="status" value="Pending"/><br> 
                <input type="submit" name="add" value="Add"/><br>                
            </form>             
            
                              
        </div>
    </body>
</html>

apps/main_app/templates/main_app/show.html
<!DOCTYPE hmtl>
<html>
    <head>
        <meta charset="utf8" />
        <meta name="descripition" content="Learning about Django"/>
        <title>Courses</title>
        
        {% load static %}
        <link rel="stylesheet" href={% static "first_app/css/index.css"  %}></link>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script type="text/javascript" src={% static "first_app/js/index.js"  %}></script> 
        <style>
            label {
                   margin:20px;
                   margin-left:0px;
                   vertical-align:top;
            }
            input {
                margin-left:40px;
                margin-bottom:10px;
            }                   
        </style>
       
    </head>
    <body>
        <div id="container"> 
            <div id="show_product" >
           
                <h4>Product {{post.name}}</h4>
                <h4>User who added thie product/itmeusder their wish list</h4>
                    {% for user in post.wished.all %}
                        <p>{{user.first_name}}</p>
                    {% endfor %}               
                
            </div>          
            <a href="{% url 'dashboard:home' %}">Home</a>   |      <a href="{% url 'home:logout' %}">Logout</a>      
        </div>
    </body>
</html>

apps/main_app/templates/main_app/update.html
<!DOCTYPE hmtl>
<html>
    <head>
        <meta charset="utf8" />
        <meta name="descripition" content="Learning about Django"/>
        <title>Courses</title>
        
        {% load static %}
        <link rel="stylesheet" href={% static "first_app/css/index.css"  %}></link>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script type="text/javascript" src={% static "first_app/js/index.js"  %}></script> 
        <style>
            label {
                   margin:20px;
                   margin-left:0px;
                   vertical-align:top;
            }
            form input {
                margin-left:40px;
                margin-bottom:10px;
            }
            form input[type=submit] {
                margin-left:400px;
                height:45px;
                width:80px;
                color:white;
                background-color:blue;
            }
            
            
            
        </style>
       
    </head>
    <body>
        <div id="container"> 
           <form  action="{% url 'dashboard:update'  task_id=appointment.id %}"  method="post">
                {% csrf_token %}
                <h4>Update Appointment</h4>
                  {% for message in messages %}
                    <p>{{ message }}</p>
                  {% endfor %}
                <label>Date:</label><input type="text" name="date" placeHolder="MM/DD/YYYY"  value='{{appointment.taskdatetime|date:"m/d/Y"}}'/><br>
                <label>Time:</label><input type="text" name="time" placeHolder="HH:MM" value='{{appointment.taskdatetime|date:"H:i"}}'/><br>
                <label>Tasks:</label><input type="text" name="task"/ value='{{appointment.task}}'><br>
                <label>Status:</label>
                <select name="status" value='{{appointment.status}}'>
                  <option value="Pending">Pending</option>
                  <option value="Done">Done</option> 
                   <option value="Missed">Missed</option>                   
                </select><br>                 
                <input type="submit" name="add" value="Update"/><br>                
            </form>         
            
             <a href="{% url 'dashboard:home' %}">Home</a>   |      <a href="{% url 'home:logout' %}">Logout</a>         
        </div>
    </body>
</html>